pipeline {
	agent any
	stages {
		stage('BUILD') {
			steps {
				sh """
				    #!bin/bash
				    pwd
				    ls -lrt
				    sleep 5
				"""
			}
		}

	stage('TEST-WINDOWS') {
			steps {
				sh """
				    #!/bin/bash
				    pwd
				    ls -lrt
				    sleep 5
			    """
				
			}
		}

		stage('TEST-LINUX') {
			steps {
				sh """
					#!/bin/bash
					pwd
					sleep 5
					ls -lrt
				"""
			}
		}

		stage('DEPLOY') {
			steps {
				sh """
					sleep 5
				"""
			}
		}	
	}
}
